### ISSUE TITLE
在docker内运行第5涨可视化的时候会出现  Pangolin X11: Failed to open X display 。是在docker内无法显示界面吗？

### ISSUE THREAD

**Issue by wayne1627** [Johnzdh/Johnzdh-slam14-docker#2]

**Comment by Dylancer1998** [comment]
是的

**Comment by wayne1627** [comment]
非常感谢。

docker run -it \
   --net=host \
   -e DISPLAY=$DISPLAY \
   -v $HOME/.Xauthority:/root/.Xauthority \
   --name slamtest \
   bodcoder2/slam14:latest

后面我看到启动时加上这些参数就可以显示了。
另外在宿主机上运行这两句
sudo apt-get install x11-xserver-utils
xhost +
